#config for the action client(goal)

type: 'square'

square:
  dist: 1.0 #in m
  num_points: 1

circ:
  rad: 2.0
  angle: 90 #angle increments of entire circle in degrees
  num_points: 1

turn:
  angle: 360 #angle increments of entire turn in degrees
  num_points: 1