#config for the action client(goal)

#0: circle
#1: square (sharp turns), 
#2: square (smooth turns)
#3: angular
  #Note: circle and angular also define two of the three primitive motions (along with linear)
type: 1

# how many times to repeat motion
repeat: 10

# use csv trajectories (0/1 F/T)? 
use_csv: 1
# if so, choose which csv file to use
csv_file: 'grid_v2.csv'

square:
  dist: 1.0 #in m
  num_points: 1

circ:
  #For normal circular motion
  rad: 0.5
  angle: 360 #angle increments of entire circle in degrees
  num_points: 1

circ_turn:
  #For quarter angle turns in smoothed square motion
  rad: 0.2
  angle: 90 #angle increments of entire circle in degrees
  num_points: 1

turn:
  angle: 360 #angle increments of entire turn in degrees
  num_points: 1