#config for the action client(goal)

#0: circle
#1: square (sharp turns), 
#2: square (smooth turns)
#3: angular
  #Note: circle and angular also define two of the three primitive motions (along with linear)
type: 0

square:
  dist: 1.0 #in m
  num_points: 1

circ:
  #For normal circular motion
  rad: 2.0
  angle: 90 #angle increments of entire circle in degrees
  num_points: 1

circ_turn:
  #For quarter angle turns in smoothed square motion
  rad: 0.2
  angle: 90 #angle increments of entire circle in degrees
  num_points: 1

turn:
  angle: 360 #angle increments of entire turn in degrees
  num_points: 1