#config for the action server(control)

type: 'circular'  #circular/square

basic:
  linear_x: 0.20    #for square motion
  angular_z: 0.32
  num_cmds: 10
  delay: 0.5

time:
  initial_delay: 2.0
  cmd_delay: 0.1

limits:
  x: 0.18
  theta: 0.18
  theta_turn: 2.7

#Current tuning scheme: Ku = 0.7, Tu = 1.2
  # PI: P = 0.45Ku = 0.315, I = 0.54Ku/Tu = 0.315
  # PD: P = 0.8Ku = 0.56, D = 0.1*Ku*Tu = 0.084
  # No overshoot: P = 0.2Ku = 0.14, I = 0.4Ku/Tu = 2.333, D = 0.056
PID_linear:
  P: 0.14 
  I: 2.333
  D: 0.056
PID_angular:
  P: 0.000
  I: 0.0
  D: 0.0

diff:
  x: 0.005
  y: 0.08 
  theta: 0.15 #~7.5 degrees  #0.009~0.5 degrees

#Circle defined by radius R = V/W
#Hard-coded values now; later should programatically calculate x/w values based on radius (arg)
#Values should ideally be:
  # Large(2m): v = 0.18, z = 0.09
  # Medium(1.5m): v = 0.18, z = 0.12
  # Small(1m): v = 0.18, z = 0.18

circle:
  #So far num_cmds is hardcoded:
    #B04 - 2 meters (2 tiles): ~144 commands
    #B05 - 1.5 meters (1 tile): ~ 78 commands
  num_cmds: 120 
  delay: 0.5
  radius: 2.0
  linear_x: 0.18



