#config for the action server(control)

type: 'circular'  #circular/square

basic:
  linear_x: 0.20    #for square motion
  angular_z: 0.32
  num_cmds: 10
  delay: 0.5

time:
  initial_delay: 2.0
  cmd_delay: 0.2

limits:
  x: 0.18
  theta: 0.18

PID:
  P: 0.2
  I: 0.0
  D: 0.0

diff:
  x: 0.1
  y: 0.1 
  theta: 0.02 #~1 degrees

#Circle defined by radius R = V/W
#Hard-coded values now; later should programatically calculate x/w values based on radius (arg)
#Values should ideally be:
  # Large(2m): v = 0.18, z = 0.09
  # Medium(1.5m): v = 0.18, z = 0.12
  # Small(1m): v = 0.18, z = 0.18

circle:
  #So far num_cmds is hardcoded:
    #B04 - 2 meters (2 tiles): ~144 commands
    #B05 - 1.5 meters (1 tile): ~ 78 commands
  num_cmds: 120 
  delay: 0.5
  radius: 2.0
  linear_x: 0.18



