#config for the action server(control)

type: 'circular'  #circular/square

line:
  num_points: 10

basic:
  linear_x: 0.20    #for square motion
  angular_z: 0.32
  num_cmds: 10
  delay: 0.5

time:
  initial_delay: 2.0
  cmd_delay: 0.05

limits:
  x: 0.18
  theta: 0.18
  theta_turn: 2.2

#Current tuning scheme: Ku = 0.7, Tu = 1.2
  # PI: P = 0.45Ku = 0.315, I = 0.54Ku/Tu = 0.315
  # PD: P = 0.8Ku = 0.56, D = 0.1*Ku*Tu = 0.084
  # No overshoot: P = 0.2Ku = 0.14, I = 0.4Ku/Tu = 0.2333, D = 2KuTu/3 = 0.56
PID_linear:
  P: 0.270 
  I: 0.315
  D: 0.00

#Current tuning scheme: Ku = 0.67, Tu = 1.1
  # PI: P = 0.45Ku = 0.3015, I = 0.54Ku/Tu = 0.3289
  # PD: P = 0.8Ku = 0.536, D = 0.1*Ku*Tu = 0.0737
  # PID: P = 0.6Ku = 0.402, I = 1.2Ku/Tu = 0.730909091, D = 0.075KuTu = 0.055275
  # No overshoot: P = 0.2Ku = 0.134, I = 0.4Ku/Tu = 0.2436, D = 2KuTu/3 = 0.4913
PID_angular:
  P: 0.280
  I: 0.3289
  D: 0.00

diff:
  x: 0.005
  y: 0.06 
  theta: 0.005 #~0.4 degrees  #0.009~0.5 degrees

#Circle defined by radius R = V/W
#Hard-coded values now; later should programatically calculate x/w values based on radius (arg)
#Values should ideally be:
  # Large(2m): v = 0.18, z = 0.09
  # Medium(1.5m): v = 0.18, z = 0.12
  # Small(1m): v = 0.18, z = 0.18

circle:
  #So far num_cmds is hardcoded:
    #B04 - 2 meters (2 tiles): ~144 commands
    #B05 - 1.5 meters (1 tile): ~ 78 commands
  num_cmds: 120 
  delay: 0.5
  radius: 2.0
  linear_x: 0.18



