type: 'circular'  #circular/square

basic:
  linear_x: 0.20    #for square motion
  angular_z: 0.32
  num_cmds: 10
  delay: 0.5

#Circle defined by radius R = V/W
#Hard-coded values now; later should programatically calculate x/w values based on radius (arg)

circle:
  num_cmds: 30
  delay: 0.5
  radius: 2.0
  linear_x: 0.18

#2 meters
circ_large:
  num_cmds: 30
  delay: 0.5
  linear_x: 0.18
  angular_z: 0.09

#1.5 meters
circ_med:
  num_cmds: 30
  delay: 0.5
  linear_x: 0.18
  angular_z: 0.12

#1 meter
circ_small:
  num_cmds: 30
  delay: 0.5
  linear_x: 0.18
  angular_z: 0.18

time:
  initial_delay: 2.0
  cmd_delay: 0.5