type: 'square'  #circular/square

basic:
  linear_x: 0.18    #for square motion
  angular_z: 0.5
  num_cmds: 5
  delay: 0.5

circular_large:
  num_cmds: 30
  delay: 0.5
  linear_x: 0.18
  angular_z: 0.14

circular_small:
  num_cmds: 30
  delay: 0.5
  linear_x: 0.16
  angular_z: 0.15

time:
  initial_delay: 2.0
  cmd_delay: 0.5